import feedparser
import requests
import logging
import os
import traceback
import time
from datetime import datetime
from google import genai
from google.genai import types

# --- 1. CONFIGURATION ---
GEMINI_KEY = os.environ.get('GEMINI_API_KEY')
DISCORD_WEBHOOK_URL = os.environ.get('DISCORD_WEBHOOK_URL') 

# Force the stable 'v1' API version to avoid 404 errors found in logs
client = genai.Client(
    api_key=GEMINI_KEY,
    http_options={'api_version': 'v1'}
)
MEMORY_FILE = "sent_urls.txt"

# --- 2. PERFORMANCE MARKETING SOURCES ---
AD_PLATFORM_SOURCES = {
    "Google Ads Blog": "https://blog.google/products/ads-commerce/rss/",
    "Search Engine Land (PPC)": "https://searchengineland.com/library/ppc/feed",
    "Social Media Today": "https://www.socialmediatoday.com/feeds/news/",
    "Marketing Dive": "https://www.marketingdive.com/feeds/news/"
}

TOOL_ASO_SOURCES = {
    "AppTweak Blog": "https://www.apptweak.com/en/aso-blog/feed",
    "Sensor Tower Blog": "https://sensortower.com/blog/rss",
    "Business of Apps": "https://www.businessofapps.com/feed/",
    "MobileDevMemo": "https://mobiledevmemo.com/feed/"
}

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

# --- 3. UTILITIES ---
def load_sent_urls():
    if not os.path.exists(MEMORY_FILE): return set()
    try:
        with open(MEMORY_FILE, "r") as f: 
            return set(line.strip() for line in f if line.strip())
    except Exception as e:
        logging.error(f"Failed to read memory: {e}")
        return set()

def save_sent_urls(urls):
    if not urls: return
    try:
        existing = list(load_sent_urls())
        combined = list(urls) + [u for u in existing if u not in urls]
        with open(MEMORY_FILE, "w") as f:
            for url in combined[:1000]: 
                f.write(f"{url}\n")
    except Exception as e:
        logging.error(f"Failed to save memory: {e}")

def fetch_data(source_dict):
    sent_urls = load_sent_urls()
    items, new_urls = [], []
    for name, url in source_dict.items():
        try:
            resp = requests.get(url, timeout=15)
            feed = feedparser.parse(resp.content)
            for entry in feed.entries[:8]:
                if entry.link not in sent_urls:
                    summary_text = entry.get('summary', '')[:300].replace('\n', ' ')
                    items.append({"source": name, "title": entry.title, "link": entry.link, "desc": summary_text})
                    new_urls.append(entry.link)
        except Exception as e: 
            logging.error(f"Fetch failed for {name}: {e}")
    return items, new_urls

# --- 4. DISCORD SENDER ---
def send_to_discord(message):
    if not DISCORD_WEBHOOK_URL:
        logging.error("No Discord Webhook URL found.")
        return
    
    payload = {
        "content": message[:1990],
        "username": "Performance Marketing Bot",
        "avatar_url": "https://cdn-icons-png.flaticon.com/512/1998/1998087.png"
    }
    
    try:
        r = requests.post(DISCORD_WEBHOOK_URL, json=payload, timeout=15)
        r.raise_for_status()
        logging.info("Successfully sent message to Discord.")
    except Exception as e:
        logging.error(f"Discord Webhook failed: {e}")

# --- 5. EXECUTION ---
def run_agent():
    logging.info("Scanning for marketing updates...")
    
    ad_items, ad_urls = fetch_data(AD_PLATFORM_SOURCES)
    tool_items, tool_urls = fetch_data(TOOL_ASO_SOURCES)

    # Logic gate to prevent sending empty prompts to the AI (prevents 400 Bad Request)
    if not ad_items and not tool_items:
        logging.info("No new news found since last check. Exiting.")
        return

    ad_summary = None
    if ad_items:
        logging.info(f"Summarizing {len(ad_items)} ad platform updates...")
        ad_summary = get_summary_safe(
            ad_items, 
            "Summarize updates for Meta, Google, TikTok, or Apple Ads. Use bullet points. Format: **Platform**: Summary (1 sentence)."
        )

    tool_summary = None
    if tool_items:
        logging.info(f"Summarizing {len(tool_items)} tool updates...")
        tool_summary = get_summary_safe(
            tool_items, 
            "Summarize updates for ASO tools (AppTweak, Sensor Tower) or industry shifts. Use bullet points. Format: **Tool**: Summary (1 sentence)."
        )

    if ad_summary or tool_summary:
        final_msg = f"# 🚀 PERFORMANCE MARKETING DAILY\n*Date: {datetime.now().strftime('%Y-%m-%d')}*\n\n"
        
        if ad_summary:
            final_msg += f"## 📡 AD PLATFORMS\n{ad_summary}\n\n"
        
        if tool_summary:
            final_msg += f"## 🛠️ TOOLS & MARKET\n{tool_summary}\n"

        send_to_discord(final_msg)
        save_sent_urls(ad_urls + tool_urls)
    else:
        logging.warning("No summaries were generated by the AI.")

def get_summary_safe(items, instruction):
    if not items: 
        return None
        
    text_blob = "\n".join([f"- [{i['source']}] {i['title']}: {i['desc']}" for i in items])
    
    if not text_blob.strip():
        return None

    try:
        # Merge instruction into prompt to avoid the "Unknown name systemInstruction" error
        full_prompt = f"{instruction}\n\nContext to summarize:\n{text_blob}"
        
        # Use gemini-1.5-flash for production stability
        response = client.models.generate_content(
            model="gemini-1.5-flash",
            contents=full_prompt
        )
        return response.text
    except Exception as e:
        logging.error(f"Gemini API Error: {e}")
        return None

if __name__ == "__main__":
    run_agent()
